# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:auth_project}
spring.datasource.username=${POSTGRES_USER:postgres-user}
spring.datasource.password=${POSTGRES_PASSWORD:secret}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate/JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.private.key=${JWT_PRIVATE_KEY:classpath:app.key}
jwt.public.key=${JWT_PUBLIC_KEY:classpath:app.pub}